table = [
    ["IDL Type", "NDR Type Defined", "C Type C Type"],
    ["boolean", "boolean", "idl_boolean", "unsigned char"],
    ["char", "character", "idl_char", "unsigned char"],
    ["byte", "uninterpreted octet", "idl_byte", "unsigned char"],
    ["small", "small", "idl_small_int", "char"],
    ["short", "short", "idl_short_int", "short int"],
    ["long", "long", "idl_long_int", "long int"],
    ["hyper", "hyper", "idl_hyper_int", "**16- or 32-Bit Machines:**"],
    ['', '', '', "**Big Endian:**"],
    ['', '', '', "`struct { long high; unsigned long low; }`"],
    ['', '', '', "**Little Endian:**"],
    ['', '', '', "`struct { unsigned long low; long high; }`"],
    ['', '', '', "**64-Bit Machines:**"],
    ['', '', '', "`long`"],
    ["unsigned small", "unsigned small", "idl_usmall_int", "unsigned char"],
    ["unsigned short", "unsigned short", "idl_ushort_int",
        "unsigned short int"],
    ["unsigned long", "unsigned long", "idl_ulong_int", "unsigned long int"],
    ["unsigned hyper", "unsigned hyper", "idl_uhyper_int",
        "****16- or 32-Bit Machines:****"],
    ['', '', '', "**Big Endian:**"],
    ['', '', '', "`struct { unsigned long high; unsigned long low; }`"],
    ['', '', '', "**Little Endian:**"],
    ['', '', '', "`struct { unsigned long low; unsigned long high; }`"],
    ['', '', '', "**64-Bit Machines:**"],
    ['', '', '', "`unsigned long`"],
    ["float", "float", "idl_float", "float"],
    ["double", "double", "idl_double", "double"],
    ["handle_t", "not transmitted", "handle_t", "`void *`"],
    ["error_status_t", "unsigned long", "idl_ulong_int", "unsigned long int"],
    ["ISO_LATIN_1", "uninterpreted octet", "ISO_LATIN_1", "`byte`"],
    ["ISO_MULTI_LINGUAL", "(Note 1.)", "ISO_MULTI_LINGUAL",
        "`struct{ byte row; byte column; }`"],
    ["ISO_UCS", "(Note 1.)", "ISO_UCS",
        "`struct{ byte group; byte plane; byte row; byte column;" "}`"]]
